//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netlenium {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralLocalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralLocalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netlenium.GeneralLocalStrings", typeof(GeneralLocalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEBUG].
        /// </summary>
        public static string Logging_WriteEntry_Debug {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEBUG][{0}]: {1} &gt; {2}{3}.
        /// </summary>
        public static string Logging_WriteEntry_DEBUG_FileFormat {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_DEBUG_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  X  ].
        /// </summary>
        public static string Logging_WriteEntry_Error {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR][{0}]: {1} &gt; {2}{3}.
        /// </summary>
        public static string Logging_WriteEntry_ERROR_FileFormat {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_ERROR_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ ~~~ ].
        /// </summary>
        public static string Logging_WriteEntry_Information {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFORMATION][{0}]: {1} &gt; {2}{3}.
        /// </summary>
        public static string Logging_WriteEntry_INFORMATION_FileFormat {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_INFORMATION_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &gt; .
        /// </summary>
        public static string Logging_WriteEntry_ModuleName {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SUCCESS][{0}]: {1} &gt; {2}{3}.
        /// </summary>
        public static string Logging_WriteEntry_SUCCESS_FileFormat {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_SUCCESS_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}]: .
        /// </summary>
        public static string Logging_WriteEntry_Timestamp {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VERBO].
        /// </summary>
        public static string Logging_WriteEntry_VERBO {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_VERBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VERBOSE][{0}]: {1} &gt; {2}{3}.
        /// </summary>
        public static string Logging_WriteEntry_VERBOSE_FileFormat {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_VERBOSE_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  !  ].
        /// </summary>
        public static string Logging_WriteEntry_Warning {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [WARNING][{0}]: {1} &gt; {2}{3}.
        /// </summary>
        public static string Logging_WriteEntry_WARNING_FileFormat {
            get {
                return ResourceManager.GetString("Logging_WriteEntry_WARNING_FileFormat", resourceCulture);
            }
        }
    }
}
